export const MOVED_START = "MOVED_START";
export const MOVED_END = "MOVED_END";


export const ADDED_ADDITIONAL_DESTINATION_NODE = "ADDED_ADDITIONAL_DESTINATION_NODE";
export const REMOVED_ADDITIONAL_DESTINATION_NODE = "REMOVED_ADDITIONAL_DESTINATION_NODE";


export const ADDED_WALL = "ADDED_WALL";
export const REMOVED_WALL = "REMOVED_WALL";

export const ADDED_WEIGHT = "ADDED_WEIGHT";
export const REMOVED_WEIGHT = "REMOVED_WEIGHT"

